Info commands are ready to be reviewed
nicex000/ShimakazeBot pull request #7
Opened 2020-10-12 12:16 UTC by michauorin

2020-10-18 10:06 UTC, IAmVisco requested changes

2020-10-29 18:39 UTC, nicex000 requested changes
yea so pretty much change the Iffy's and replace the RespondAsync.
don't see anything else myself

2020-11-02 19:49 UTC, nicex000 approved these changes

2020-11-02 20:50 UTC, IAmVisco requested changes

2020-11-03 11:41 UTC, IAmVisco approved these changes

2020-11-03 11:44 UTC, merged