Purge - Ban - Kick - Warn
nicex000/ShimakazeBot pull request #8
Opened 2020-10-29 11:34 UTC by nicex000

and some utility for basic embeds

don't look at the first warn command commit, only reason i actually did a commit with it is to do profiling with mich one day

2020-10-30 21:39 UTC, michauorin requested changes
Minor revision requested,
mostly about naming, but i'd suggest a different type for the embed factory,
cause you still modify the embed after it's returned from that, so that would
make the intent clear (as in it's not a ready to post embed, it's still a builder).

2020-11-03 18:12 UTC, michauorin approved these changes

2020-11-05 14:13 UTC, IAmVisco requested changes

2020-11-06 18:08 UTC, IAmVisco approved these changes

2020-11-06 18:19 UTC, merged